-- vim-workout: Motion skills
-- Defines all motion-related skills (Tiers 1-5)

local M = {}

M.skills = {
  -- Tier 1: Foundations
  {
    id = "motion_hjkl",
    name = "Basic Movement",
    key = "h/j/k/l",
    type = "motion",
    tier = 1,
    description = "Move cursor left (h), down (j), up (k), or right (l)",
    prerequisites = {},
  },

  -- Tier 2: Word Motions
  {
    id = "motion_w",
    name = "Word Forward",
    key = "w",
    type = "motion",
    tier = 2,
    description = "Move forward to the start of the next word",
    prerequisites = { "motion_hjkl" },
  },
  {
    id = "motion_b",
    name = "Word Backward",
    key = "b",
    type = "motion",
    tier = 2,
    description = "Move backward to the start of the previous word",
    prerequisites = { "motion_hjkl" },
  },
  {
    id = "motion_e",
    name = "End of Word",
    key = "e",
    type = "motion",
    tier = 2,
    description = "Move forward to the end of the current/next word",
    prerequisites = { "motion_hjkl" },
  },
  {
    id = "motion_W",
    name = "WORD Forward",
    key = "W",
    type = "motion",
    tier = 2,
    description = "Move forward to the start of the next WORD (whitespace-delimited)",
    prerequisites = { "motion_w" },
  },
  {
    id = "motion_B",
    name = "WORD Backward",
    key = "B",
    type = "motion",
    tier = 2,
    description = "Move backward to the start of the previous WORD",
    prerequisites = { "motion_b" },
  },
  {
    id = "motion_E",
    name = "End of WORD",
    key = "E",
    type = "motion",
    tier = 2,
    description = "Move forward to the end of the current/next WORD",
    prerequisites = { "motion_e" },
  },

  -- Tier 3: Line Motions
  {
    id = "motion_0",
    name = "Line Start",
    key = "0",
    type = "motion",
    tier = 3,
    description = "Move to the first column of the line",
    prerequisites = { "motion_w", "motion_b" },
  },
  {
    id = "motion_caret",
    name = "First Non-Blank",
    key = "^",
    type = "motion",
    tier = 3,
    description = "Move to the first non-blank character of the line",
    prerequisites = { "motion_0" },
  },
  {
    id = "motion_dollar",
    name = "Line End",
    key = "$",
    type = "motion",
    tier = 3,
    description = "Move to the end of the line",
    prerequisites = { "motion_w", "motion_b" },
  },

  -- Tier 4: Character Search
  {
    id = "motion_f",
    name = "Find Character",
    key = "f{char}",
    type = "motion",
    tier = 4,
    description = "Move forward to the next occurrence of {char}",
    prerequisites = { "motion_0", "motion_dollar" },
  },
  {
    id = "motion_t",
    name = "Till Character",
    key = "t{char}",
    type = "motion",
    tier = 4,
    description = "Move forward to just before the next occurrence of {char}",
    prerequisites = { "motion_f" },
  },
  {
    id = "motion_F",
    name = "Find Backward",
    key = "F{char}",
    type = "motion",
    tier = 4,
    description = "Move backward to the previous occurrence of {char}",
    prerequisites = { "motion_f" },
  },
  {
    id = "motion_T",
    name = "Till Backward",
    key = "T{char}",
    type = "motion",
    tier = 4,
    description = "Move backward to just after the previous occurrence of {char}",
    prerequisites = { "motion_t", "motion_F" },
  },
  {
    id = "motion_semicolon",
    name = "Repeat Find",
    key = ";",
    type = "motion",
    tier = 4,
    description = "Repeat the last f, t, F, or T motion",
    prerequisites = { "motion_f", "motion_t" },
  },
  {
    id = "motion_comma",
    name = "Repeat Find Reverse",
    key = ",",
    type = "motion",
    tier = 4,
    description = "Repeat the last f, t, F, or T motion in reverse",
    prerequisites = { "motion_semicolon" },
  },

  -- Tier 5: File Navigation
  {
    id = "motion_gg",
    name = "Go to Top",
    key = "gg",
    type = "motion",
    tier = 5,
    description = "Move to the first line of the file (or line N with Ngg)",
    prerequisites = { "motion_0", "motion_dollar" },
  },
  {
    id = "motion_G",
    name = "Go to Bottom",
    key = "G",
    type = "motion",
    tier = 5,
    description = "Move to the last line of the file (or line N with NG)",
    prerequisites = { "motion_gg" },
  },
  {
    id = "motion_percent",
    name = "Matching Bracket",
    key = "%",
    type = "motion",
    tier = 5,
    description = "Move to the matching bracket (), [], {}",
    prerequisites = { "motion_f" },
  },
  {
    id = "motion_brace_open",
    name = "Paragraph Up",
    key = "{",
    type = "motion",
    tier = 5,
    description = "Move to the previous blank line (paragraph boundary)",
    prerequisites = { "motion_gg" },
  },
  {
    id = "motion_brace_close",
    name = "Paragraph Down",
    key = "}",
    type = "motion",
    tier = 5,
    description = "Move to the next blank line (paragraph boundary)",
    prerequisites = { "motion_G" },
  },
}

return M
